import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';

export default function Home() {
  const [target, setTarget] = useState('');
  const [entries, setEntries] = useState([]);
  const SECRET_KEY = process.env.NEXT_PUBLIC_SECRET_KEY;

  const rephrase = async (e) => {
    e.preventDefault();
    const data = {
      prompt: target,
      temperature: 0.5,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    };

    const res = await fetch(
      'https://api.openai.com/v1/engines/text-curie-001/completions',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${SECRET_KEY}`,
        },
        body: JSON.stringify(data),
      }
    );
    const response = await res.json();

    setEntries([
      ...entries,
      { initialEntry: data.prompt, reply: response.choices[0].text },
    ]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>GPT-3 Contell Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>GPT-3 Contell Dictionary</h1>

        <p className={styles.description}>Let an AI rephrase you.</p>
        <div>
          <form>
            <input
              type="text"
              name="target"
              id="target"
              value={target}
              onChange={(e) => setTarget(e.target.value)}
            />
            <button type="submit" onClick={rephrase}>
              rephrase!
            </button>
          </form>
        </div>
        <div className={styles.grid}>
          {entries.map((entry, index) => {
            return (
              <div className={styles.card} key={index}>
                <h3>{entry.initialEntry}</h3>
                <p>{entry.reply}</p>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://alexcontell.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <h3>Alex Contell</h3>
        </a>
      </footer>
    </div>
  );
}
